---
title: "date_compare"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
date_compare <- function(sem_vec, faculty, module, plot = FALSE){
  res_allSem <- lapply(sem_vec, module_data, faculty = faculty, module = module)
  # save the infomrations in date.frame
  sem_info <- unlist(sapply(res_allSem, function(x){x[17]}))
  date_info <- unlist(sapply(res_allSem, function(x){x[12]}))
  mean_info  <- unlist(sapply(res_allSem, function(x){x[18]}))
  mean_info <- as.numeric(gsub("-", NA,  mean_info))
  info_df <- na.omit(data.frame(sem_info,date_info, mean_info)) 
  info_df$date_info <- as.Date(info_df[,2], "%d.%m.%Y") 
  # extract the information for the second date
  second_mean_all <- data.frame(matrix(ncol = 1))
  for (i in 1:(length(info_df[,1])-1 )) {
    if (info_df[i,1] == info_df[i+1,1]) {
      second_mean_all[i,] <- info_df[i,3]  
    }
  }
  # compute mean for second date
  second_mean_all <- na.omit(second_mean_all)
  second_mean_all <- as.numeric(second_mean_all[,1])
  second_mean <- mean(second_mean_all)
  # extract the information for the first date
  first_mean_all <- data.frame(matrix(ncol = 1))
  for (i in 1:(length(info_df[,1])-1 )) {
    if (info_df[i,1] == info_df[i+1,1]) {
      first_mean_all[i,] <- info_df[i+1,3]  
    }
  }
  # compute mean for first date
  first_mean_all <- na.omit(first_mean_all)
  first_mean_all <- as.numeric(first_mean_all[,1])
  first_mean <- mean(first_mean_all)
  result <- data.frame(first_mean, second_mean)
  if (plot == FALSE){
    return(result)
  } else{
    df <- data.frame(Mean_Grades=as.numeric(result[1,]), date_names=c("First date", "Second date"))
    ggplot(df, aes(x=df$date_names, y=df$Mean_Grades, fill=df$date_names)) +
      geom_bar(stat = "identity") + 
      xlab("Examination date") + ylab("Mean grades") +
      coord_cartesian(ylim=c(min(df$Mean_Grades-0.5),max(df$Mean_Grades)+0.5)) +
      guides(fill=guide_legend(title=NULL)) +
      ggtitle("First vs. second examination date")
  }
}
```
